version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
      - ./db.sqlite:/app/db.sqlite
    environment:
      - OLLAMA_BASE_URL=http://ollama-server:11434
      - MODEL_NAME=qwen2.5-coder:0.5b
    depends_on:
      - ollama-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  ollama-server:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  ollama-data: